version: "3.6"
services:

  api:
    build: .
    environment:
      DATABASE_NAME: "tyre_app"
      IP_SERVER: "167.235.253.89"
      PORT_SERVER: 10099

    volumes:
      - ./:/main
#    ports:
#      - "10099:10099"
    network_mode: "host"
